### ISSUE TITLE
Cannot open database "dev/stderr" {sqlserver)

### ISSUE THREAD

**Issue by hogank3** [slingdata-io/sling-cli#19]
### Issue: Execution fails when loading to SQL Server due to bcp utility command.

**Description:**

- **Problem:** Execution fails when trying to load data into SQL Server.
- **Probable Cause:** There seems to be an issue with the bcp utility command, specifically with the `-e` flag.
- **Verification:** I created a simple csv and tried running the bcp command which also failed with the same error.
- **Temporary Solution:** By removing the `"-e /dev/stderr"` parameter, the load is successful.

**Documentation Reference:**  
The [Microsoft documentation](https://learn.microsoft.com/en-us/sql/tools/bcp-utility?view=sql-server-ver16#-e-err_file) mentions that the `-e` flag should have a full path to the error file. It also states not to have a space between `-e` and the path if the path starts with a forward slash or hyphen.

**Recommendation:**  
If the code can be updated to specify a full path for the error file, this issue might be resolved. However, I couldn't pinpoint the exact location in the codebase where this is happening.

```cmd
>> sling run -c C:\extract.yaml

3:17PM INF connecting to source database (oracle)
3:17PM INF connecting to target database (sqlserver)
3:17PM INF reading from source database
3:18PM INF writing to target database [mode: full-refresh]
3:18PM INF streaming data
54s 56,845 1064 r/s
3:19PM INF execution failed
fatal:
~
~ failure running task (see docs @ https://docs.slingdata.io/sling-cli)
~
~ execution failed
context canceled

~ could not bulk import
context canceled

~ SQL Server BCP Import Command -> bcp dbo.testtable_tmp in C:\Users\kevin\AppData\Local\Temp\sqlserver.dbo.testtable_tmp.1.csv2503925445 -S **** -d Test_DW_L -U Test_Login -P **** -t , -m 1 -c -q -b 50000 -F 2 -e /dev/stderr      
SQL Server BCP Import Error  ->
SQLState = 37000, NativeError = 4060
Error = [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot open database "ev/stderr" requested by the login. The login failed.
SQLState = 28000, NativeError = 18456
Error = [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user 'Test_Login'.

exit status 1

~ could not insert into "dbo"."TestTable"
context canceled

~ could not bulk import
context canceled

~ SQL Server BCP Import Command -> bcp dbo.testtable_tmp in C:\Users\kevin\AppData\Local\Temp\sqlserver.dbo.testtable_tmp.1.csv2503925445 -S **** -d Test_DW_L -U Test_Login -P **** -t , -m 1 -c -q -b 50000 -F 2 -e /dev/stderr      
SQL Server BCP Import Error  ->
SQLState = 37000, NativeError = 4060
Error = [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot open database "ev/stderr" requested by the login. The login failed.
SQLState = 28000, NativeError = 18456
Error = [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user 'Test_Login'.

exit status 1
```

**Comment by flarco** [comment]
Thank you for the details. 

Yes, I see. The `/dev/error` is specific to unix systems, so this should not be used on Windows systems, let me take a look.

In the meantime, as a work-around, can you provide `use_bulk: false` under `target.options`, so it does not use `bcp`? See [Target Options](https://docs.slingdata.io/sling-cli/running-tasks#target-options-tgt-options-flag-target.options-key) in the docs. It will load slower, but should work.

**Comment by hogank3** [comment]
Ah, I see. I can confirm ```use_bulk: false``` is slower but works. Thank you for the suggestion and the quick reply!

**Comment by flarco** [comment]
@nickolay fyi about using `use_bulk: false`. See above if you are facing the same issue.

**Comment by nickolay** [comment]
Thanks for the heads-up!

I'll share the right incantation because I barely managed to come up with it before giving up:

* `--tgt-options {'use_bulk':false}` (the key must be quoted, otherwise it's silently ignored)
* or `-c config.json` with `{"target":{"options":{"use_bulk": false}}}` (which I found from the source of the python CLI; I didn't find out what the [docs](https://docs.slingdata.io/sling-cli/running-tasks) meant by "YAML Configuration Text")

I don't think the doc sources are in github, right?

**Comment by flarco** [comment]
> --tgt-options {'use_bulk':false} (the key must be quoted, otherwise it's silently ignored)

Ah, I can see how that it is confusing. It accepts YAML or JSON syntax, but it has to be surrounded by quotes from the command line.

- YAML syntax: `--tgt-options '{use_bulk: false}'`
- JSON syntax: `--tgt-options '{"use_bulk": false}'`

> I didn't find out what the [docs](https://docs.slingdata.io/sling-cli/running-tasks) meant by "YAML Configuration Text"

I'll try to make that more clear in the docs, thanks for feedback. 

> I don't think the doc sources are in github, right?

The docs are on github but private. It makes sense to make it public, will plan that, thanks. 👍

**Comment by flarco** [comment]
@hogank3 can you run `sling update`, and try again with latest version? I had some issues with `bcp` version 15 on Windows. But using version 17 on Mac and version 18 on WSL worked great.

**Comment by hogank3** [comment]
I'm using bcp version 15 on Windows. Based on the [Microsoft docs](https://learn.microsoft.com/en-us/sql/tools/bcp-utility?view=sql-server-ver16#version-information), that seems to be the latest version for Windows.

While troubleshooting, I noticed the temporary file bcp was using in AppData\Local\temp. I was able to reproduce the error running bcp commands manually on that file,
```
[Microsoft][ODBC Driver 17 for SQL Server]Unable to open BCP host data-file
```
After some investigation, I discovered the temp file had LF line endings. Changing these to CRLF resolved the issue, which would also explain why Mac and Linux weren't affected.

I apologize, I am still not familiar enough with the project yet to pinpoint the code causing the issue. But I hope the information helps!


On a separate note, this error output in Sling reveals the server name and password when printing the failed bcp command. I noticed previously those values were masked, which was a welcome feature for security reasons.

**Comment by flarco** [comment]
Ah yes, I was troubleshooting and accidentally left the masking off. Will add that back in, thanks for raising that.

OK, great. I will have the temp CSV writer use CRLF, thanks for discovering that! I actually checked the line endings with Notepad++ and it showed CRLF, so I must have missed something. Will test and release soon.

**Comment by hogank3** [comment]
Would it work to add something along the lines of ```w.UseCRLF = (runtime.GOOS == "windows")``` after this [line](https://github.com/flarco/dbio/blob/14beef27817b17d1e406b1b759d2b0fd0d014ceb/iop/csv.go#L375)?

I am guessing WriteStream is where the temp file is created.

**Comment by flarco** [comment]
It's actually [here](https://github.com/flarco/dbio/blob/14beef27817b17d1e406b1b759d2b0fd0d014ceb/database/database_sqlserver.go#L566).

So, I could actually use your thoughts on this. When I initially wrote the BCP import logic, whenever a string value had a new line, or quotes, the Go CSV writer would correctly surround the value with quotes and escape (per standard). But the BCP program would not recognize it with the quotes. Whenever the value would go onto the next line inside the surrounded quotes, or had the escaped _double_ quote, it would error out. I am guessing this is fixed in the newer versions of BCP (haven't tested yet), but this would need to be backward compatible.

To deal with this, my thought was to create the `writeCsvWithoutQuotes` function ([here](https://github.com/flarco/dbio/blob/14beef27817b17d1e406b1b759d2b0fd0d014ceb/database/database_sqlserver.go#L566)), where the quotes and the new line are replaced by placeholders. You can see the list [here](https://github.com/flarco/dbio/blob/14beef27817b17d1e406b1b759d2b0fd0d014ceb/database/database_sqlserver.go#L152-L156) where a new line for example is replaced by `$~n$~` prior the load, then after the load, an UPDATE statement is ran the replace the placeholders back to the original values (see [here](https://github.com/flarco/dbio/blob/14beef27817b17d1e406b1b759d2b0fd0d014ceb/database/database_sqlserver.go#L250-284)). A little crazy I know, but it worked. As you can see in the comment, `reduces performance by ~25%, but is correct, and still 10x faster then INSERT INTO with batch VALUES`.

Any thoughts on this? This logic was written 3 years ago, but is worth a good revisit. I guess we could just use the BCP version obtained [here](https://github.com/flarco/dbio/blob/14beef27817b17d1e406b1b759d2b0fd0d014ceb/database/database_sqlserver.go#L364), and write the CSV with quotes if BCP is a high enough version? Probably will be faster then having to UPDATE after load.

**Comment by hogank3** [comment]
I did some testing with version 15, and it seems it still has issues handling quoted fields. The limitations mentioned in your [stackoverflow](https://stackoverflow.com/questions/782353/sql-server-bulk-insert-of-csv-file-with-inconsistent-quotes) reference are still in place. I can see why you chose the approach you did.

However, I noticed that new lines and quotes primarily cause problems when they are present in the first or last fields. That might offer an opportunity to regain some performance by reducing the number of columns placeholder characters are applied to. To illustrate, the csv below loads correctly via bcp, though it does look unconventional. On the other hand, delimiters within data fields will always cause problems as they did before, regardless of where they are located.

This behavior is consistent with versions 15.0.4298.1 and 12.0.6024.0 (the earliest I had on hand). Not much of an improvement, I know, but it's all I can think of at the moment considering the limitations the bcp utility. I would say at the very least it would be worth sticking to your current approach given the speed improvement it already provides.

```csv
COL1,COL2,COL3
1,REGULAR COLUMN,TEST1
2,

NEW
LINES IN 

COLUMN,TEST2
3,QUOTES" IN"" COLUMN,TEST3
```

**Comment by flarco** [comment]
@hogank3 just released a new version with the changes discussed (`1.0.45`). Can you give it a try?

**Comment by hogank3** [comment]
I updated to `1.0.47` this morning and still encountered similar errors, but the temp files looked correct.

However, after updating to `1.0.48`, it is working without needing the `use_bulk: false` option.

**Comment by flarco** [comment]
Thanks, yes, there was an issue with Go holding the temp file open, which collided in Windows, but worked fine in Linux/Mac.  Fixed that in 1.0.48. Thanks for all the testing.

**Comment by nickolay** [comment]
> writeCsvWithoutQuotes function, where the quotes and the new line are replaced by placeholders

bcp is actually [documented](https://learn.microsoft.com/en-us/sql/relational-databases/import-export/use-character-format-to-import-or-export-data-sql-server?view=sql-server-ver16#considerations-for-using-character-format) to use a format simpler than CSV, where rows are separated by the specified Row Terminator, and fields are separated by a Field Terminator (so, no quoting at all).

So instead of messing with temporary placeholders, you could let the user specify the [supported terminators](https://learn.microsoft.com/en-us/sql/relational-databases/import-export/specify-field-and-row-terminators-sql-server?view=sql-server-ver16#characters-supported-as-terminators) (e.g. `\0\0\t`, `\n\0\0`, use those in `writeCsvWithoutQuotes` instead of `,` and `\n`, and pass them on to `bcp`.

**Comment by flarco** [comment]
Interesting, thanks, will plan on using those.
