### ISSUE TITLE
Bug on COPY INTO stage with Snowflake target

### ISSUE THREAD

**Issue by inesplc** [slingdata-io/sling-cli#440]
## Issue Description

- Description of the issue: 

**The replication is looking for stage in the `PUBLIC` instead of the target schema**

I have a replication pipeline with two streams that read from a Snowflake account (`SNOWFLAKE_HEAP`) and write to a different one (`SNOWFLAKE_CS`) which is behaving in a weird way.

It fails with the error `Stage 'RAW.PUBLIC.SLING_STAGING' does not exist or not authorized.` when:
- I have set the role as `accountadmin` to rule out permission errors
- There is no stage in the schema `PUBLIC`. There is one, however, in the target schema `authdb`
```sql
> show stages in schema RAW.PUBLIC;
Query produced no results

> show stages in schema RAW.AUTHDB;
```
created_on | name | database_name | schema_name | url | has_credentials | has_encryption_key | owner | comment | region | type | cloud | notification_channel | storage_integration | endpoint | owner_role_type | directory_enabled
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2024-11-14 16:05:15.981 -0800 | SLING_STAGING | RAW | AUTHDB |   | N | N | SYSADMIN |   |   | INTERNAL |   |   |   |   | ROLE | N

Interestingly enough, if I remove one of the streams and keep only the one raising the error, the replication is successful:
```yml
streams:
  authdb.public_partner_apps:
    primary_key: [id]
    mode: full-refresh
````

- Sling version (`sling --version`): 
```sh
» sling --version
Version: 1.2.22
```

- Operating System (`linux`, `mac`, `windows`): 
`macOS 15.1`

- Replication Configuration: 

```yaml
source: SNOWFLAKE_HEAP
target: SNOWFLAKE_CS

defaults:
  object: "HEAP_POSTGRES.AUTHDB__{stream_table}"

  source_options:
    empty_as_null: false

  target_options:
    column_casing: snake

streams:
  authdb.partner_apps:
    primary_key: [id]
    mode: full-refresh
  authdb.public_partner_apps:
    primary_key: [id]
    mode: full-refresh
```

<details><summary>Log Output (please run command with `-d`): </summary>

(please ignore the `Unable to expand env_var` warnings, these are from unrelated dbt projects)

```
sling run -r replication_test.yml -d                                                                                                   1 ↵ ines@PV6T2XLL77
2024-11-18 11:30:52 WRN Unable to expand env_var 'SECRET_DEV_SERVICE_DBT_PWD' for dbt profile bi_dbt / dev-ae, key password
2024-11-18 11:30:52 WRN Unable to expand env_var 'SECRET_DEV_SERVICE_DBT_USER' for dbt profile bi_dbt / dev-ae, key user
2024-11-18 11:30:52 WRN Unable to expand env_var 'SECRET_DEV_SERVICE_DBT_USER' for dbt profile bi_dbt / dev-rst-all-ci, key user
2024-11-18 11:30:52 WRN Unable to expand env_var 'SECRET_DEV_SERVICE_DBT_PWD' for dbt profile bi_dbt / dev-rst-all-ci, key password
2024-11-18 11:30:52 WRN Unable to expand env_var 'SECRET_DEV_SERVICE_DBT_USER' for dbt profile bi_dbt / dev-rst-ppl-ci, key user
2024-11-18 11:30:52 WRN Unable to expand env_var 'SECRET_DEV_SERVICE_DBT_PWD' for dbt profile bi_dbt / dev-rst-ppl-ci, key password
2024-11-18 11:30:52 WRN Unable to expand env_var 'SECRET_DEV_SERVICE_DBT_USER' for dbt profile bi_dbt / dev-rst-fin-ci, key user
2024-11-18 11:30:52 WRN Unable to expand env_var 'SECRET_DEV_SERVICE_DBT_PWD' for dbt profile bi_dbt / dev-rst-fin-ci, key password
2024-11-18 11:30:52 WRN Unable to expand env_var 'SECRET_DEV_SERVICE_DBT_USER' for dbt profile bi_dbt / dev-ae-ci, key user
2024-11-18 11:30:52 WRN Unable to expand env_var 'SECRET_DEV_SERVICE_DBT_PWD' for dbt profile bi_dbt / dev-ae-ci, key password
2024-11-18 11:30:52 WRN Unable to expand env_var 'SECRET_DEV_SERVICE_DBT_USER' for dbt profile bi_dbt / dev-rst-ppl, key user
2024-11-18 11:30:52 WRN Unable to expand env_var 'SECRET_DEV_SERVICE_DBT_PWD' for dbt profile bi_dbt / dev-rst-ppl, key password
2024-11-18 11:30:52 WRN Unable to expand env_var 'SECRET_DEV_SERVICE_DBT_USER' for dbt profile bi_dbt / dev-rst-fin, key user
2024-11-18 11:30:52 WRN Unable to expand env_var 'SECRET_DEV_SERVICE_DBT_PWD' for dbt profile bi_dbt / dev-rst-fin, key password
2024-11-18 11:30:52 WRN Unable to expand env_var 'SECRET_DEV_SERVICE_DBT_USER' for dbt profile bi_dbt / dev-da, key user
2024-11-18 11:30:52 WRN Unable to expand env_var 'SECRET_DEV_SERVICE_DBT_PWD' for dbt profile bi_dbt / dev-da, key password
2024-11-18 11:30:52 WRN Unable to expand env_var 'SECRET_DEV_SERVICE_DBT_PWD' for dbt profile bi_dbt / dev-da-ci, key password
2024-11-18 11:30:52 WRN Unable to expand env_var 'SECRET_DEV_SERVICE_DBT_USER' for dbt profile bi_dbt / dev-da-ci, key user
2024-11-18 11:30:52 WRN Unable to expand env_var 'SECRET_DEV_SERVICE_DBT_USER' for dbt profile bi_dbt / dev-rst-all, key user
2024-11-18 11:30:52 WRN Unable to expand env_var 'SECRET_DEV_SERVICE_DBT_PWD' for dbt profile bi_dbt / dev-rst-all, key password
2024-11-18 11:30:52 WRN Unable to expand env_var 'SECRET_DEV_SERVICE_DBT_USER' for dbt profile bi_dbt / dev, key user
2024-11-18 11:30:52 WRN Unable to expand env_var 'SECRET_DEV_SERVICE_DBT_PWD' for dbt profile bi_dbt / dev, key password
2024-11-18 11:30:52 WRN Unable to expand env_var 'SECRET_DEV_SERVICE_DBT_USER' for dbt profile bi_dbt / dev-ci, key user
2024-11-18 11:30:52 WRN Unable to expand env_var 'SECRET_DEV_SERVICE_DBT_PWD' for dbt profile bi_dbt / dev-ci, key password
2024-11-18 11:30:52 INF Sling Replication [2 streams] | SNOWFLAKE_HEAP -> SNOWFLAKE_CS

2024-11-18 11:30:52 INF [1 / 2] running stream authdb.partner_apps
2024-11-18 11:30:52 DBG Sling version: 1.2.22 (darwin arm64)
2024-11-18 11:30:52 DBG type is db-db
2024-11-18 11:30:52 DBG using: {"columns":null,"mode":"full-refresh","transforms":null}
2024-11-18 11:30:52 DBG using source options: {"empty_as_null":false,"null_if":"NULL","datetime_format":"AUTO","max_decimals":-1}
2024-11-18 11:30:52 DBG using target options: {"datetime_format":"auto","file_max_rows":0,"max_decimals":-1,"use_bulk":true,"add_new_columns":true,"adjust_column_type":false,"column_casing":"snake"}
2024-11-18 11:30:53 DBG opened "snowflake" connection (conn-snowflake-9N5)
2024-11-18 11:30:55 DBG opened "snowflake" connection (conn-snowflake-wBA)
2024-11-18 11:30:56 INF connecting to source database (snowflake)
2024-11-18 11:30:57 INF connecting to target database (snowflake)
2024-11-18 11:30:57 INF reading from source database
2024-11-18 11:30:59 DBG REMOVE @sling_staging/sling_temp/1731929459437
2024-11-18 11:30:59 DBG COPY INTO '@sling_staging/sling_temp/1731929459437/01_'
from (select * from "AUTHDB"."PARTNER_APPS")
FILE_FORMAT = (
  TYPE = CSV
  RECORD_DELIMITER = '\n'
  NULL_IF = '\\N'
  COMPRESSION = GZIP
  ESCAPE_UNENCLOSED_FIELD = NONE
  FIELD_OPTIONALLY_ENCLOSED_BY = '0x22'
)
HEADER = TRUE
2024-11-18 11:31:00 DBG Unloaded 304 rows to @sling_staging/sling_temp/1731929459437
2024-11-18 11:31:00 DBG LIST @sling_staging/sling_temp/1731929459437
2024-11-18 11:31:01 DBG GET @sling_staging/sling_temp/1731929459437 'file:///var/folders/_n/6krc72z52cdc4_2r2bj9cqk00000gn/T/snowflake/get/2024-11-18T113059.437' overwrite=true parallel=10
2024-11-18 11:31:02 DBG 
+--------------------------------+-------+------------+---------+
| FILE                           |  SIZE | STATUS     | MESSAGE |
+--------------------------------+-------+------------+---------+
| 1731929459437/01__0_0_0.csv.gz | 15800 | DOWNLOADED |         |
+--------------------------------+-------+------------+---------+
2024-11-18 11:31:02 DBG REMOVE @sling_staging/sling_temp/1731929459437
2024-11-18 11:31:02 DBG opened "file" connection (conn-file-HwF)
2024-11-18 11:31:02 DBG reading single datastream from  [format=csv]
2024-11-18 11:31:02 DBG merging csv readers of 1 files [concurrency=3] from 
2024-11-18 11:31:02 DBG processing reader from file:///var/folders/_n/6krc72z52cdc4_2r2bj9cqk00000gn/T/snowflake/get/2024-11-18T113059.437/01__0_0_0.csv.gz
2024-11-18 11:31:02 DBG casting column 'client_id' as 'text'
2024-11-18 11:31:02 DBG casting column 'created_by' as 'text'
2024-11-18 11:31:02 DBG casting column 'env_id' as 'bigint'
2024-11-18 11:31:02 DBG casting column 'id' as 'bigint'
2024-11-18 11:31:02 DBG casting column 'oauth_redirect_uri' as 'text'
2024-11-18 11:31:02 DBG casting column 'setup_restricted' as 'bool'
2024-11-18 11:31:02 DBG casting column 'user_mapping' as 'text'
2024-11-18 11:31:02 DBG casting column '_sdc_batched_at' as 'timestampz'
2024-11-18 11:31:02 DBG casting column '_sdc_received_at' as 'timestampz'
2024-11-18 11:31:02 DBG casting column '_sdc_sequence' as 'bigint'
2024-11-18 11:31:02 DBG casting column '_sdc_table_version' as 'bigint'
2024-11-18 11:31:02 INF writing to target database [mode: full-refresh]
2024-11-18 11:31:03 DBG drop table if exists "HEAP_POSTGRES"."AUTHDB__PARTNER_APPS_TMP"
2024-11-18 11:31:03 DBG table "HEAP_POSTGRES"."AUTHDB__PARTNER_APPS_TMP" dropped
2024-11-18 11:31:03 DBG create transient table "HEAP_POSTGRES"."AUTHDB__PARTNER_APPS_TMP" ("CLIENT_ID" text,
"CREATED_BY" text,
"ENV_ID" bigint,
"ID" bigint,
"OAUTH_REDIRECT_URI" text,
"SETUP_RESTRICTED" boolean,
"USER_MAPPING" text,
"_SDC_BATCHED_AT" timestamp_tz,
"_SDC_RECEIVED_AT" timestamp_tz,
"_SDC_SEQUENCE" bigint,
"_SDC_TABLE_VERSION" bigint)
2024-11-18 11:31:03 INF created table "HEAP_POSTGRES"."AUTHDB__PARTNER_APPS_TMP"
2024-11-18 11:31:03 INF streaming data
2024-11-18 11:31:04 DBG USE SCHEMA HEAP_POSTGRES
2024-11-18 11:31:04 DBG opened "file" connection (conn-file-QmZ)
2024-11-18 11:31:04 DBG writing to file:///var/folders/_n/6krc72z52cdc4_2r2bj9cqk00000gn/T/snowflake/put/heap_postgres.authdb__partner_apps_tmp/2024-11-18T113104.089/part.01 [fileRowLimit=0 fileBytesLimit=300000000 compression=zstd concurrency=7 useBufferedStream=false fileFormat=csv singleFile=false]
2024-11-18 11:31:04 DBG REMOVE @HEAP_POSTGRES.sling_staging/heap_postgres.authdb__partner_apps_tmp/2024-11-18T113104.089
2024-11-18 11:31:04 DBG PUT 'file:///var/folders/_n/6krc72z52cdc4_2r2bj9cqk00000gn/T/snowflake/put/heap_postgres.authdb__partner_apps_tmp/2024-11-18T113104.089/part.01.0001.csv.zst' @HEAP_POSTGRES.sling_staging/heap_postgres.authdb__partner_apps_tmp/2024-11-18T113104.089 PARALLEL=10 AUTO_COMPRESS=FALSE
2024-11-18 11:31:04 DBG COPY INTO "HEAP_POSTGRES"."AUTHDB__PARTNER_APPS_TMP" ("CLIENT_ID", "CREATED_BY", "ENV_ID", "ID", "OAUTH_REDIRECT_URI", "SETUP_RESTRICTED", "USER_MAPPING", "_SDC_BATCHED_AT", "_SDC_RECEIVED_AT", "_SDC_SEQUENCE", "_SDC_TABLE_VERSION")
from ( 
  select T.$1, T.$2, T.$3, T.$4, T.$5, T.$6, T.$7, T.$8, T.$9, T.$10, T.$11
  from @HEAP_POSTGRES.sling_staging/heap_postgres.authdb__partner_apps_tmp/2024-11-18T113104.089 as T
)
FILE_FORMAT = (
  TYPE = CSV
  RECORD_DELIMITER = '\n'
  ESCAPE_UNENCLOSED_FIELD = NONE
  FIELD_OPTIONALLY_ENCLOSED_BY = '0x22'
  EMPTY_FIELD_AS_NULL = FALSE
  NULL_IF = '\\N'
  SKIP_HEADER = 1
  REPLACE_INVALID_CHARACTERS = TRUE
)
ON_ERROR = ABORT_STATEMENT
2024-11-18 11:31:05 DBG 
+-------------------------------------------------------------------------------------------------+--------+-------------+-------------+
| FILE                                                                                            | STATUS | ROWS_LOADED | ERRORS_SEEN |
+-------------------------------------------------------------------------------------------------+--------+-------------+-------------+
| sling_staging/heap_postgres.authdb__partner_apps_tmp/2024-11-18T113104.089/part.01.0001.csv.zst | LOADED |         304 |           0 |
+-------------------------------------------------------------------------------------------------+--------+-------------+-------------+
2024-11-18 11:31:06 DBG select count(*) cnt from "HEAP_POSTGRES"."AUTHDB__PARTNER_APPS_TMP"
2024-11-18 11:31:06 DBG drop table if exists "HEAP_POSTGRES"."AUTHDB__PARTNER_APPS"
2024-11-18 11:31:06 DBG table "HEAP_POSTGRES"."AUTHDB__PARTNER_APPS" dropped
2024-11-18 11:31:07 DBG create table "HEAP_POSTGRES"."AUTHDB__PARTNER_APPS" ("CLIENT_ID" text,
"CREATED_BY" text,
"ENV_ID" bigint,
"ID" bigint,
"OAUTH_REDIRECT_URI" text,
"SETUP_RESTRICTED" boolean,
"USER_MAPPING" text,
"_SDC_BATCHED_AT" timestamp_tz,
"_SDC_RECEIVED_AT" timestamp_tz,
"_SDC_SEQUENCE" bigint,
"_SDC_TABLE_VERSION" bigint)
2024-11-18 11:31:07 INF created table "HEAP_POSTGRES"."AUTHDB__PARTNER_APPS"
2024-11-18 11:31:07 DBG insert into "HEAP_POSTGRES"."AUTHDB__PARTNER_APPS" ("CLIENT_ID", "CREATED_BY", "ENV_ID", "ID", "OAUTH_REDIRECT_URI", "SETUP_RESTRICTED", "USER_MAPPING", "_SDC_BATCHED_AT", "_SDC_RECEIVED_AT", "_SDC_SEQUENCE", "_SDC_TABLE_VERSION") select "CLIENT_ID", "CREATED_BY", "ENV_ID", "ID", "OAUTH_REDIRECT_URI", "SETUP_RESTRICTED", "USER_MAPPING", "_SDC_BATCHED_AT", "_SDC_RECEIVED_AT", "_SDC_SEQUENCE", "_SDC_TABLE_VERSION" from "HEAP_POSTGRES"."AUTHDB__PARTNER_APPS_TMP"
2024-11-18 11:31:08 DBG inserted rows into "HEAP_POSTGRES"."AUTHDB__PARTNER_APPS" from temp table "HEAP_POSTGRES"."AUTHDB__PARTNER_APPS_TMP"
2024-11-18 11:31:08 INF inserted 304 rows into "HEAP_POSTGRES"."AUTHDB__PARTNER_APPS" in 16 secs [19 r/s] [61 kB]
2024-11-18 11:31:08 DBG drop table if exists "HEAP_POSTGRES"."AUTHDB__PARTNER_APPS_TMP"
2024-11-18 11:31:08 DBG table "HEAP_POSTGRES"."AUTHDB__PARTNER_APPS_TMP" dropped
2024-11-18 11:31:08 DBG closed "snowflake" connection (conn-snowflake-wBA)
2024-11-18 11:31:08 INF execution succeeded

2024-11-18 11:31:09 INF [2 / 2] running stream authdb.public_partner_apps
2024-11-18 11:31:09 DBG Sling version: 1.2.22 (darwin arm64)
2024-11-18 11:31:09 DBG type is db-db
2024-11-18 11:31:09 DBG using: {"columns":null,"mode":"full-refresh","transforms":null}
2024-11-18 11:31:09 DBG using source options: {"empty_as_null":false,"null_if":"NULL","datetime_format":"AUTO","max_decimals":-1}
2024-11-18 11:31:09 DBG using target options: {"datetime_format":"auto","file_max_rows":0,"max_decimals":-1,"use_bulk":true,"add_new_columns":true,"adjust_column_type":false,"column_casing":"snake"}
2024-11-18 11:31:09 INF connecting to source database (snowflake)
2024-11-18 11:31:10 INF connecting to target database (snowflake)
2024-11-18 11:31:11 DBG opened "snowflake" connection (conn-snowflake-j4f)
2024-11-18 11:31:11 INF reading from source database
2024-11-18 11:31:12 DBG REMOVE @sling_staging/sling_temp/1731929472270
2024-11-18 11:31:12 DBG COPY INTO '@sling_staging/sling_temp/1731929472270/01_'
from (select * from "AUTHDB"."PUBLIC_PARTNER_APPS")
FILE_FORMAT = (
  TYPE = CSV
  RECORD_DELIMITER = '\n'
  NULL_IF = '\\N'
  COMPRESSION = GZIP
  ESCAPE_UNENCLOSED_FIELD = NONE
  FIELD_OPTIONALLY_ENCLOSED_BY = '0x22'
)
HEADER = TRUE
2024-11-18 11:31:12 ERR 002003 (02000): SQL compilation error:
Stage 'RAW.PUBLIC.SLING_STAGING' does not exist or not authorized. error="--- database_snowflake.go:662 func1 ---\n--- database.go:1166 Query ---\n~ Error with StreamRows\n--- database.go:1179 QueryContext ---\n~ SQL Error for:\nCOPY INTO '@sling_staging/sling_temp/1731929472270/01_'\nfrom (select * from \"AUTHDB\".\"PUBLIC_PARTNER_APPS\")\nFILE_FORMAT = (\n  TYPE = CSV\n  RECORD_DELIMITER = '\\n'\n  NULL_IF = '\\\\N'\n  COMPRESSION = GZIP\n  ESCAPE_UNENCLOSED_FIELD = NONE\n  FIELD_OPTIONALLY_ENCLOSED_BY = '0x22'\n)\nHEADER = TRUE\n--- database.go:827 StreamRowsContext ---\n002003 (02000): SQL compilation error:\nStage 'RAW.PUBLIC.SLING_STAGING' does not exist or not authorized."
2024-11-18 11:31:12 DBG REMOVE @sling_staging/sling_temp/1731929472270
2024-11-18 11:31:13 INF execution failed

--- database_snowflake.go:662 func1 ---
~ SQL Error for @sling_staging/sling_temp/1731929472270/01_
--- database.go:1166 Query ---
~ Error with StreamRows
--- database.go:1179 QueryContext ---
~ SQL Error for:
COPY INTO '@sling_staging/sling_temp/1731929472270/01_'
from (select * from "AUTHDB"."PUBLIC_PARTNER_APPS")
FILE_FORMAT = (
  TYPE = CSV
  RECORD_DELIMITER = '\n'
  NULL_IF = '\\N'
  COMPRESSION = GZIP
  ESCAPE_UNENCLOSED_FIELD = NONE
  FIELD_OPTIONALLY_ENCLOSED_BY = '0x22'
)
HEADER = TRUE
--- database.go:827 StreamRowsContext ---
002003 (02000): SQL compilation error:
Stage 'RAW.PUBLIC.SLING_STAGING' does not exist or not authorized.

context canceled

2024-11-18 11:31:13 INF Sling Replication Completed in 20s | SNOWFLAKE_HEAP -> SNOWFLAKE_CS | 1 Successes | 1 Failures


fatal:
--- proc.go:271 main ---
--- sling_cli.go:458 main ---
--- sling_cli.go:494 cliInit ---
--- cli.go:286 CliProcess ---
~ failure running replication (see docs @ https://docs.slingdata.io/sling-cli)
--- sling_run.go:209 processRun ---

--------------------------- authdb.public_partner_apps ---------------------------
--- task_run.go:116 func2 ---
~ Could not ReadFromDB
--- task_run.go:541 runDbToDb ---
~ Could not BulkExportFlow
--- task_run_read.go:184 ReadFromDB ---
~ Could not unload to stage.
--- database_snowflake.go:239 BulkExportFlow ---
~ Could not unload to stage files
--- database_snowflake.go:686 UnloadViaStage ---

--- database_snowflake.go:662 func1 ---
~ SQL Error for @sling_staging/sling_temp/1731929472270/01_
--- database.go:1166 Query ---
~ Error with StreamRows
--- database.go:1179 QueryContext ---
~ SQL Error for:
COPY INTO '@sling_staging/sling_temp/1731929472270/01_'
from (select * from "AUTHDB"."PUBLIC_PARTNER_APPS")
FILE_FORMAT = (
  TYPE = CSV
  RECORD_DELIMITER = '\n'
  NULL_IF = '\\N'
  COMPRESSION = GZIP
  ESCAPE_UNENCLOSED_FIELD = NONE
  FIELD_OPTIONALLY_ENCLOSED_BY = '0x22'
)
HEADER = TRUE
--- database.go:827 StreamRowsContext ---
002003 (02000): SQL compilation error:
Stage 'RAW.PUBLIC.SLING_STAGING' does not exist or not authorized.
```

</details>

**Comment by flarco** [comment]
Hi, interesting. Is the schema set to `PUBLIC` to either connection?
Also, in the Snowflake UI, is `PUBLIC` the default schema to either?

**Comment by inesplc** [comment]
hey @flarco, thanks for looking into this

> Is the schema set to PUBLIC to either connection?

Nope, none of the connections have the `schema` configured, only the database
```yml
connections:
  SNOWFLAKE_CS:
    type: snowflake
    account: xxxxxxx
    user: xxxxxxx
    password: xxxxxxx
    database: dev_raw
    role: xxxxxxx
    warehouse: xxxxxxx


  SNOWFLAKE_HEAP:
    type: snowflake
    host: xxxxxxx
    user: xxxxxxx
    password: xxxxxxx
    database: raw
    role: accountadmin
    warehouse: xxxxxxx
```

> Also, in the Snowflake UI, is PUBLIC the default schema to either?

Not sure if there's a better way to look for this info, but the `PUBLIC` schema is the one that automatically shows at the top of the list for both connections:

**Snowflake_HEAP**
![image](https://github.com/user-attachments/assets/4ee30cb2-7c07-44b8-9a8b-ee9e88a4332f)

**Snowflake_CS**
![image](https://github.com/user-attachments/assets/b1711891-a39b-4bcd-975d-69e45ac3a943)

**Comment by inesplc** [comment]
hey @flarco, was the above enough information? 🙂

**Comment by flarco** [comment]
That's interesting, this is the first I've heard of this behavior.

I pushed a change. Can you try it with the [dev build](https://github.com/slingdata-io/sling-cli?tab=readme-ov-file#automated-dev-builds)?

**Comment by inesplc** [comment]
@flarco that worked!

```sh
» ~/Downloads/sling --version
Version: 1.2.23.dev (2024-11-20)

» ~/Downloads/sling run -r replication_test.yml 
11:56AM INF Sling Replication [2 streams] | SNOWFLAKE_HEAP -> SNOWFLAKE_CS

11:56AM INF [1 / 2] running stream authdb.partner_apps
11:56AM INF connecting to source database (snowflake)
11:56AM INF connecting to target database (snowflake)
11:56AM INF reading from source database
11:56AM INF writing to target database [mode: full-refresh]
11:56AM INF created table "HEAP_POSTGRES"."AUTHDB__PARTNER_APPS_TMP"
11:56AM INF streaming data
11:56AM INF created table "HEAP_POSTGRES"."AUTHDB__PARTNER_APPS"
11:56AM INF inserted 305 rows into "HEAP_POSTGRES"."AUTHDB__PARTNER_APPS" in 14 secs [21 r/s] [61 kB]
11:56AM INF execution succeeded

11:56AM INF [2 / 2] running stream authdb.public_partner_apps
11:56AM INF connecting to source database (snowflake)
11:56AM INF connecting to target database (snowflake)
11:56AM INF reading from source database
11:56AM INF writing to target database [mode: full-refresh]
11:56AM INF created table "HEAP_POSTGRES"."AUTHDB__PUBLIC_PARTNER_APPS_TMP"
11:56AM INF streaming data
11:56AM INF created table "HEAP_POSTGRES"."AUTHDB__PUBLIC_PARTNER_APPS"
11:56AM INF inserted 33 rows into "HEAP_POSTGRES"."AUTHDB__PUBLIC_PARTNER_APPS" in 11 secs [3 r/s] [7.5 kB]
11:56AM INF execution succeeded

11:56AM INF Sling Replication Completed in 27s | SNOWFLAKE_HEAP -> SNOWFLAKE_CS | 2 Successes | 0 Failures
```

Would it be possible to release this ASAP?

**Comment by flarco** [comment]
Will release this weekend.

**Comment by miriamcastel** [comment]
After updating to version 1.2.23, the job ran successfully for a few days.

Nonetheless, the issue came back.

Is there something we can do to facilitate the investigation @flarco?
